name: 7net Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check stock
        shell: bash
        run: |
          PAGE=$(curl -L -s "https://7net.omni7.jp/detail/2110695509")

          if echo "$PAGE" | grep -q "カートに入れる"; then
            MESSAGE=$'🟢 7net CÓ HÀNG!\nhttps://7net.omni7.jp/detail/2110695509'
          else
            MESSAGE="🔴 7net vẫn hết hàng."
          fi

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.CHAT_ID }}" \
            --data-urlencode text="$MESSAGE"
