name: 7net Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check stock
        run: |
          echo "checking 7net"

          curl -s "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          --data-urlencode "text=Bot 7net đã chạy thử thành công"
